switch underlying matrix library from gomatrix to mautrix-go
metio/matrix-alertmanager-receiver pull request #37
Opened 2024-08-30 11:58 UTC by metskem

Since the gomatrix library is no longer supported, I think we should switch to mautrix-go.

2024-08-30 12:26 UTC, sebhoss commented
Thanks a lot!

AFAIK the room joining part was added so that the initial setup in a complete new rooms works fine, e.g. in our case we have to invite the bot account to a room and the bot has to somehow accept that invitation before being able to send messages. Does this work in the new library without doing an explicit join?

2024-08-30 12:52 UTC, metskem commented
Ah, I missed that. And no, I don't think mautrix-go will allow uninvited members to send messages either. So that would have to be added back in again. 
In our test cases we explicitly invited the bot account and also logged in with the bot account to accept the invite.
If you have time please add it, or I can do it somewhere during the weekend or Monday.

2024-08-30 12:54 UTC, sebhoss commented
Ok ok - let see who is faster :smile:

2024-08-31 05:05 UTC, sebhoss requested changes

2024-08-31 05:05 UTC, sebhoss commented on internal/matrix/client.go
> -	}, []string{"room"})
Can we add these back or do they somehow break something somewhere?

2024-09-02 04:09 UTC, sebhoss approved these changes

2024-09-02 04:12 UTC, merged

2024-09-02 04:13 UTC, sebhoss commented
@metskem thanks a lot!